version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./files/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
volumes:
  db_data: